version: '1'
services:
  microserviciob:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@myc9t6cno9rq2ggr_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=java_bd2
      - spring.datasource.password=ClaseFullStack1-
    restart: always